package com.application.aled.entity;

public enum TypeProfil {
    /**
<<<<<<< HEAD
	HYPERTENSION,
	DIABETE,
	AUTONOME,
	NON_AUTONOME,
	SPORTIF,
	NON_SPORTIF,
	SOCIABLE,
	NON_SOCIABLE,
	JEUX,
	CUISINE,
	REPOS,
	BON_ETAT_SOCIAL,
	MAUVAIS_ETAT_SOCIAL,
	BON_ETAT_FINANCIER,
	MAUVAIS_ETAT_FINANCIER
=======
    SICK,
    NO_SICK,
    SELF_RULING,
    NO_SELF_RULING,
    ATHLETIC,
    NO_ATHLETIC,
    SOCIABLE,
    NO_SOCIABLE,
    LIKE_GAMES,
    LIKE_COOKING,
    LIKE_REST,
    GOOD_SOCIAL_STATE,
    BAD_SOCIAL_STATE,
    GOOD_FINANCIAL_STATEMENT,
    BAD_FINANCIAL_STATEMENT
>>>>>>> bc2c45a5f6de9e7602ce126471faff83eee345ff

*/
}
